#!/usr/bin/env php
<?php

// Load Composer's autoloader
require_once __DIR__ . '/../../vendor/autoload.php';


// Load environment variables from the .env file in the root directory
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/../../');
$dotenv->load();

/**
 * Used to run entity creation etc...
 */

use App\DB\DatabaseManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

ConsoleRunner::run(
    new SingleManagerProvider(DatabaseManager::getInstance()->getEntityManager())
);
